version: '2'
services:
    jhipwithmysql-mysql:
        container_name: jhipwithmysql-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/jhipwithmysql/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipwithmysql
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
